Rental_shop/Rental_shop/urls.py
from django.contrib import admin
from django.urls import path,include

from django.contrib import admin
from django.urls import path, include, re_path

urlpatterns = [
    path('admin/', admin.site.urls),
    path('rent_app/', include('rent_app.urls')),

]

Rental_shop/rent_app/urls.py
from django.urls import path
from . import views

urlpatterns = [
    path('home/', views.home, name='home'),
    path('profile/', views.profile, name='profile'),
    path('login/', views.login_view, name='login'),
    path('logout/', views.logout_view, name='logout'),
    path('register/', views.register, name='register'),
    path('rent_car/<int:car_id>/', views.rent_car, name='rent_car'),
    path('return_car/<int:rental_id>/', views.return_car, name='return_car'),
    path('export/xml/', views.export_cars_xml, name='export_xml'),
    path('export/xls/', views.export_users_xls, name='export_xls'),
    path('validate_field/', views.validate_field, name='validate_field'),
    path('account_activation_sent/', views.account_activation_sent, name='account_activation_sent'),
    path('activate/<uidb64>/<token>/', views.activate, name='activate'),
    path('some-success-page/', views.some_success_view, name='some-success-page'),
]

Rental_shop/rent_app/models.py
from django.core.exceptions import ValidationError
from datetime import timedelta
from django.db import models
from django.contrib.auth.models import User
from django.db.models.signals import post_save
from django.dispatch import receiver


class Car(models.Model):
    make = models.CharField(max_length=50)
    model = models.CharField(max_length=50)
    year = models.IntegerField()
    daily_rate = models.DecimalField(max_digits=8, decimal_places=2)
    is_rented = models.BooleanField(default=False)

    def __str__(self):
        return f"{self.make} {self.model} ({self.year})"
class RentalRecord(models.Model):
    user = models.ForeignKey(User, on_delete=models.CASCADE)
    car = models.ForeignKey(Car, on_delete=models.CASCADE)
    start_date = models.DateField()
    end_date = models.DateField()
    total_cost = models.DecimalField(max_digits=8, decimal_places=2)

    def clean(self):
        super().clean()
        if self.start_date and self.end_date:
            if (self.end_date - self.start_date) > timedelta(days=7):
                raise ValidationError("Rental period cannot exceed one week.")
        else:
            raise ValidationError("Both start date and end date are required.")


class CustomerProfile(models.Model):
    user = models.OneToOneField(User, on_delete=models.CASCADE)
    contact_number = models.CharField(max_length=15, blank=True)
    address = models.TextField(blank=True)
    driving_license = models.CharField(max_length=50, blank=True)

    def __str__(self):
        return self.user.username


@receiver(post_save, sender=User)
def create_or_update_user_profile(sender, instance, created, **kwargs):
    if created:
        CustomerProfile.objects.create(user=instance)
    else:
        CustomerProfile.objects.get_or_create(user=instance)

Rental_shop/rent_app/forms.py
from .models import RentalRecord, Car
from django import forms
from django.contrib.auth.forms import UserCreationForm
from django.contrib.auth.models import User
from django.contrib.auth.password_validation import validate_password
from django.core.exceptions import ValidationError

class RentalRecordForm(forms.ModelForm):
    car = forms.ModelChoiceField(queryset=Car.objects.none(), widget=forms.HiddenInput())

    class Meta:
        model = RentalRecord
        fields = ['start_date', 'end_date', 'car']

    def __init__(self, *args, **kwargs):
        car_id = kwargs.pop('car_id', None)
        super(RentalRecordForm, self).__init__(*args, **kwargs)
        if car_id:
            self.fields['car'].queryset = Car.objects.filter(id=car_id)




class CustomUserCreationForm(UserCreationForm):
    email = forms.EmailField(required=True)

    class Meta:
        model = User
        fields = ("username", "email", "password1", "password2")

    def clean_password1(self):
        password1 = self.cleaned_data.get("password1")
        try:
            validate_password(password1, self.instance)
        except ValidationError as error:
            self.add_error("password1", error)
        return password1

from .models import CustomerProfile

class CustomerProfileForm(forms.ModelForm):
    class Meta:
        model = CustomerProfile
        fields = ['contact_number', 'address', 'driving_license']

Rental_shop/rent_app/views.py
from django.contrib.auth.decorators import login_required
from django.contrib.auth import authenticate, login
from django.contrib.auth.forms import AuthenticationForm
from django.http import HttpResponseRedirect, HttpResponseForbidden
from django.contrib.auth import get_user_model
from django.utils.http import urlsafe_base64_decode
from django.utils.encoding import force_str
from django.contrib import messages
from django.contrib.auth import logout
from .models import Car, RentalRecord, CustomerProfile
from django.core.exceptions import ValidationError
from django.shortcuts import render, redirect, get_object_or_404
from django.contrib.auth.decorators import login_required
from .models import Car
from .forms import RentalRecordForm, CustomerProfileForm
from django.template.loader import render_to_string
from django.core.mail import send_mail
from django.contrib.sites.shortcuts import get_current_site
from django.http import HttpResponseRedirect
from django.utils.http import urlsafe_base64_encode
from django.utils.encoding import force_bytes
from .tokens import account_activation_token
from xml.etree.ElementTree import Element, SubElement, tostring

def home(request):
    available_cars = Car.objects.filter(is_rented=False)
    print("Home view called, cars:", available_cars)  # For debugging
    return render(request, 'rent_app/home.html', {'cars': available_cars})


@login_required
def profile(request):
    try:
        customer_profile = request.user.customerprofile
    except CustomerProfile.DoesNotExist:
        customer_profile = CustomerProfile(user=request.user)

    if request.method == 'POST':
        form = CustomerProfileForm(request.POST, instance=customer_profile)
        if form.is_valid():
            form.save()
            messages.success(request, 'Profile updated successfully.')
            return redirect('profile')
    else:
        form = CustomerProfileForm(instance=customer_profile)

    rentals = RentalRecord.objects.filter(user=request.user)
    return render(request, 'rent_app/profile.html', {'form': form, 'rentals': rentals})

def login_view(request):
    if request.method == 'POST':
        form = AuthenticationForm(request, request.POST)
        if form.is_valid():
            user = form.get_user()
            login(request, user)
            return HttpResponseRedirect('/rent_app/profile/')
    else:
        form = AuthenticationForm()
    return render(request, 'rent_app/login.html', {'form': form})


def logout_view(request):
    logout(request)
    return redirect('/rent_app/home/')


@login_required
def rent_car(request, car_id):
    car = get_object_or_404(Car, id=car_id, is_rented=False)
    if request.method == 'POST':
        form = RentalRecordForm(request.POST, car_id=car_id)
        if form.is_valid():
            rental = form.save(commit=False)
            rental.user = request.user
            rental.car = car
            rental_period = rental.end_date - rental.start_date
            rental.total_cost = rental.car.daily_rate * rental_period.days

            try:
                rental.full_clean()
                rental.save()
                car.is_rented = True
                car.save()
                messages.success(request, "Car rented successfully.")
                return redirect('profile')
            except ValidationError as e:
                for field, errors in e.message_dict.items():
                    for error in errors:
                        form.add_error(field, error)

    else:
        form = RentalRecordForm(car_id=car_id, initial={'car': car})

    context = {
        'form': form,
        'selected_car': car,
        'form_submitted': request.method == 'POST'
    }
    return render(request, 'rent_app/rental_form.html', context)



def register(request):
    if request.method == 'POST':
        form = CustomUserCreationForm(request.POST)
        if form.is_valid():
            user = form.save(commit=False)
            user.is_active = False
            user.save()

            current_site = get_current_site(request)
            subject = 'Activate Your Rent-a-Car Account'
            uid = urlsafe_base64_encode(force_bytes(user.pk))
            token = account_activation_token.make_token(user)

            activation_link = f"http://{current_site.domain}/rent_app/activate/{uid}/{token}/"

            message = render_to_string('rent_app/activation_email.html', {
                'user': user,
                'activation_link': activation_link
            })
            send_mail(subject, message, 'from@example.com', [user.email], fail_silently=False)

            return HttpResponseRedirect('/rent_app/account_activation_sent')
    else:
        form = CustomUserCreationForm()
    return render(request, 'rent_app/register.html', {'form': form})

@login_required
def return_car(request, rental_id):
    rental = RentalRecord.objects.filter(id=rental_id, user=request.user).first()
    if not rental:
        return HttpResponseForbidden("You cannot return a car you did not rent.")

    car = rental.car
    car.is_rented = False
    car.save()
    rental.delete()
    return HttpResponseRedirect('/rent_app/profile/')



def export_cars_xml(request):
    cars = Car.objects.all()
    root = Element('Cars')

    for car in cars:
        car_element = SubElement(root, 'Car')
        make = SubElement(car_element, 'Make')
        make.text = car.make
        model = SubElement(car_element, 'Model')
        model.text = car.model
        year = SubElement(car_element, 'Year')
        year.text = str(car.year)
        daily_rate = SubElement(car_element, 'DailyRate')
        daily_rate.text = str(car.daily_rate)

    response = HttpResponse(tostring(root), content_type='text/xml')
    response['Content-Disposition'] = 'attachment; filename="cars.xml"'
    return response

import xlwt
from django.http import HttpResponse

def export_users_xls(request):
    response = HttpResponse(content_type='application/ms-excel')
    response['Content-Disposition'] = 'attachment; filename="users.xls"'

    wb = xlwt.Workbook(encoding='utf-8')
    ws = wb.add_sheet('Users')

    row_num = 0
    font_style = xlwt.XFStyle()
    font_style.font.bold = True

    columns = ['Username', 'First name', 'Last name', 'Email']

    for col_num in range(len(columns)):
        ws.write(row_num, col_num, columns[col_num], font_style)

    font_style = xlwt.XFStyle()

    rows = User.objects.all().values_list('username', 'first_name', 'last_name', 'email')
    for row in rows:
        row_num += 1
        for col_num in range(len(row)):
            ws.write(row_num, col_num, row[col_num], font_style)

    wb.save(response)
    return response


import json
from django.http import JsonResponse
from django.views.decorators.csrf import csrf_exempt
from .forms import CustomUserCreationForm
from django.contrib.auth.models import User

@csrf_exempt
def validate_field(request):
    data = json.loads(request.body)
    field_name = data['fieldName']
    value = data['value']

    field_data = {field_name: value}

    form = CustomUserCreationForm(field_data)

    if form.is_valid() or field_name not in form.errors:
        return JsonResponse({'is_valid': True})
    else:
        error = form.errors[field_name][0]
        return JsonResponse({'is_valid': False, 'error': error})

def account_activation_sent(request):
    return render(request, 'rent_app/account_activation_sent.html')




def activate(request, uidb64, token):
    User = get_user_model()
    try:
        uid = force_str(urlsafe_base64_decode(uidb64))
        user = User.objects.get(pk=uid)
    except(TypeError, ValueError, OverflowError, User.DoesNotExist):
        user = None

    if user is not None and account_activation_token.check_token(user, token):
        user.is_active = True
        user.save()
        return redirect('some-success-page')
    else:
        messages.error(request, 'The activation link is invalid or has expired.')
        return redirect('home')

def some_success_view(request):
    return render(request, 'rent_app/some_success_page.html')

Rental_shop/rent_app/templates/rent_app/account_activation_sent.html
{% load static %}

<!DOCTYPE html>
<html lang="en">
<head>
    <meta charset="UTF-8">
    <title>Account Activation Sent</title>
    {% load static %}
    <link rel="stylesheet" href="{% static 'rent_app/css/account_activation_sent.css' %}">
</head>
<body>
    <div class="container">
        <h1>Account Activation Email Sent</h1>
        <p>Please check your email to activate your account.</p>
    </div>
</body>
</html>

Rental_shop/rent_app/templates/rent_app/activation_email.html
{% load static %}

<!DOCTYPE html>
<html lang="en">
<head>
    <meta charset="UTF-8">
    <meta name="viewport" content="width=device-width, initial-scale=1.0">
    <title>Account Activation</title>
    <link rel="stylesheet" href="{% static 'rent_app/css/email.css' %}">
</head>
<body>
    <div class="container">
        <h1>Welcome to Rent-a-Car!</h1>
        <p>Thank you for registering with us. Please click the link below to activate your account:</p>
        <a href="{{ activation_link }}" class="button">Activate Account</a>
        <p>If the button doesn't work, please copy and paste the following link in your browser:</p>
        <p>{{ activation_link }}</p>
    </div>
</body>
</html>

Rental_shop/rent_app/templates/rent_app/activation_invalid.html
{% extends 'rent_app/base.html' %}

{% block content %}
    <div class="activation-invalid">
        <h2>Activation Failed</h2>
        <p>Sorry, your account activation has failed. The link may be invalid or expired.</p>
        <p>If you think this is a mistake, please contact our support or try registering again.</p>
        <p>
            <a href="{% url 'home' %}">Return to Home</a>
        </p>
    </div>
{% endblock %}

Rental_shop/rent_app/templates/rent_app/base.html
{% load static %}
<!DOCTYPE html>
<html lang="en">
<head>
    <meta charset="UTF-8">
    <meta name="viewport" content="width=device-width, initial-scale=1.0">
    <link rel="stylesheet" href="{% static 'rent_app/css/styles.css' %}">
    <title>{% block title %}Rent-a-Car{% endblock %}</title>
    {% block extra_css %}{% endblock %}
</head>
<body>
    <header>
        <h1>Rent-a-Car</h1>
    </header>

    <nav>
        <ul>
        <li><a href="{% url 'home' %}" class="nav-link">Home</a></li>
        {% if user.is_authenticated %}
            <li><a href="{% url 'profile' %}" class="nav-link">Profile</a></li>
            <li><a href="{% url 'logout' %}" class="nav-link">Logout</a></li>
        {% else %}
            <li><a href="{% url 'login' %}" class="nav-link">Login</a></li>
            <li><a href="{% url 'register' %}" class="nav-link">Register</a></li>
        {% endif %}
        </ul>
    </nav>


    <main>
        {% block content %}
        {% endblock %}
    </main>

    <footer>
        <p>&copy; 2024 Rent-a-Car</p>
    </footer>
    {% block extra_js %}{% endblock %}

</body>
</html>

Rental_shop/rent_app/templates/rent_app/home.html
{% extends 'rent_app/base.html' %}
{% load static %}

{% block title %}Rent-a-Car{% endblock %}

{% block content %}
    <main>
    <button id="info-button" class="button">Show Info</button>
    <div id="info-container" style="display: none;"></div>
        {% for car in cars %}
            <div class="car">
                <h3>{{ car.make }} {{ car.model }} ({{ car.year }})</h3>
                <p>Daily Rate: ${{ car.daily_rate }}</p>
                {% if user.is_authenticated %}
                    <form action="{% url 'rent_car' car.id %}" method="post">
                        {% csrf_token %}
                        <button type="submit" class="rent-button">Rent This Car</button>
                    </form>
                {% else %}
                    <p>You must <a href="{% url 'login' %}">log in</a> or <a href="{% url 'register' %}">create an account</a> to rent a car.</p>
                {% endif %}
            </div>
        {% empty %}
            <p>No cars available at the moment.</p>
        {% endfor %}
    </main>
{% endblock %}

{% block extra_js %}
    <script src="{% static 'rent_app/js/scripts.js' %}"></script>
{% endblock %}

Rental_shop/rent_app/templates/rent_app/login.html
{% load static %}

<!DOCTYPE html>
<html lang="en">
<head>
    <meta charset="UTF-8">
    <meta name="viewport" content="width=device-width, initial-scale=1.0">
    <title>Login</title>
    <link rel="stylesheet" href="{% static 'rent_app/css/styles.css' %}">
</head>
<body>

<header>
    <h1>Rent-a-Car</h1>
</header>

<nav>
    <ul>
        <li><a href="{% url 'home' %}">Home</a></li>
        {% if user.is_authenticated %}
            <li><a href="{% url 'profile' %}">Profile</a></li>
            <li><a href="{% url 'logout' %}">Logout</a></li>
        {% else %}
            <li class="active"><a href="{% url 'login' %}">Login</a></li>
            <li><a href="{% url 'register' %}">Register</a></li>
        {% endif %}
    </ul>
</nav>

<main>
    <div class="login-container">
        <h2>Login</h2>
        <form method="post">
            {% csrf_token %}
            {{ form.as_p }}
            <button type="submit" class="button">Login</button>
        </form>
    </div>
</main>

<footer>
    <p>&copy; 2024 Rent-a-Car</p>
</footer>

<script src="{% static 'rent_app/js/scripts.js' %}"></script>
</body>
</html>

Rental_shop/rent_app/templates/rent_app/profile.html
{% extends 'rent_app/base.html' %}

{% load static %}
{% block content %}
  <link rel="stylesheet" type="text/css" href="{% static 'rent_app/css/profile.css' %}">
  <h2>Welcome to Your Profile, {{ user.username }}!</h2>

  {% if rentals %}
    <h3>Your Rental History:</h3>
    <ul class="profile-ul">
      {% for rental in rentals %}
        <li>{{ rental.car }} - {{ rental.start_date }} to {{ rental.end_date }}</li>
        <form method="post" action="{% url 'return_car' rental.id %}">
          {% csrf_token %}
          <button type="submit" class="button">Return Car</button>
        </form>
      {% endfor %}
    </ul>
  {% else %}
    <p>No rental history available.</p>
  {% endif %}
  {% if user.is_authenticated and user.is_staff %}
    <a href="{% url 'export_xml' %}" class="btn">Download XML</a>
    <a href="{% url 'export_xls' %}" class="btn">Download XLS</a>
  {% endif %}
    <h2>Edit Your Profile</h2>
  <form method="post">
    {% csrf_token %}
    {{ form.as_p }}
    <button type="submit" class="button">Save Profile</button>
  </form>

{% endblock %}

Rental_shop/rent_app/templates/rent_app/register.html
{% extends 'rent_app/base.html' %}
{% load static %}

{% block content %}
  <h2>Register</h2>
  <form method="post" action="{% url 'register' %}" id="registrationForm">
    {% csrf_token %}
    <div>
  <label for="id_username">Username:</label>
  {{ form.username }}
  <span id="username_error" class="error-message">{{ form.username.errors }}</span>
</div>
<div>
  <label for="id_email">Email:</label>
  {{ form.email }}
  <span id="email_error" class="error-message">{{ form.email.errors }}</span>
</div>
<div>
  <label for="id_password1">Password:</label>
  {{ form.password1 }}
  <span id="password1_error" class="error-message">{{ form.password1.errors }}</span>
</div>
<div>
  <label for="id_password2">Confirm Password:</label>
  {{ form.password2 }}
  <span id="password2_error" class="error-message">{{ form.password2.errors }}</span>
</div>

    <button type="submit" class="button">Register</button>
  </form>

  <script src="{% static 'rent_app/js/register.js' %}"></script>
{% endblock %}

Rental_shop/rent_app/templates/rent_app/rental_form.html
{% extends 'rent_app/base.html' %}

{% block content %}
    <h2>Rent Car - {{ selected_car.make }} {{ selected_car.model }} ({{ selected_car.year }})</h2>
    <form method="post">
        {% csrf_token %}
        {% if form.non_field_errors %}
            <div class="error-message">
                {% for error in form.non_field_errors %}
                    {{ error }}
                {% endfor %}
            </div>
        {% endif %}
        <div>
            <label for="id_start_date">Start Date:</label>
            {{ form.start_date }}
            {% if form_submitted and form.start_date.errors %}
                <span class="error-message">{{ form.start_date.errors }}</span>
            {% endif %}
        </div>
        <div>
            <label for="id_end_date">End Date:</label>
            {{ form.end_date }}
            {% if form_submitted and form.end_date.errors %}
                <span class="error-message">{{ form.end_date.errors }}</span>
            {% endif %}
        </div>
        <input type="hidden" name="car" value="{{ selected_car.id }}">
        <button type="submit" class="button">Rent Car</button>
    </form>
{% endblock %}

Rental_shop/rent_app/templates/rent_app/some_success_page.html
{% extends 'rent_app/base.html' %}

{% load static %}

{% block extra_css %}
<link rel="stylesheet" href="{% static 'rent_app/css/some_success_page.css' %}">
{% endblock %}

{% block content %}
  <div class="success-container">
    <h1>Account Activation Successful</h1>
    <p>Your email has been successfully verified. You can now log in and enjoy our services.</p>
    <a href="{% url 'home' %}" class="home-button">Go to Home Page</a>
  </div>
{% endblock %}